FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app
EXPOSE 8080
EXPOSE 8081


FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["QuestShare.Server/QuestShare.Server/QuestShare.Server.csproj", "QuestShare.Server/"]
COPY ["QuestShare.Server/QuestShare.Common/QuestShare.Common/QuestShare.Common.csproj", "QuestShare.Common/QuestShare.Common/"]
RUN dotnet restore "./QuestShare.Server/QuestShare.Server.csproj"
COPY . .
WORKDIR "/src/QuestShare.Server"
RUN dotnet build "./QuestShare.Server.csproj" -c $BUILD_CONFIGURATION -o /src/build /p:UseAppHost=false

# This stage is used to publish the service project to be copied to the final stage
FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./QuestShare.Server/QuestShare.Server.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
RUN dotnet tool install --global dotnet-ef
ENV PATH="$PATH:/root/.dotnet/tools"
RUN dotnet ef database update
ENTRYPOINT ["dotnet", "QuestShare.Server.dll"]